version: "3"
services:
  node:
    image: uconn/local:latest
    ports:
      - "3000:3000"
    volumes:
      - ./.entrypoint/server-entrypoint.sh:/entrypoint.sh
      - ./:/project
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/db